### ISSUE TITLE
Design Q-function

### ISSUE THREAD

**Issue by TheVeggydude** [TheVeggydude/MARL-lockdown#15]
The following Q-value function needs to be impemented:

Q(s_t0, a_t0) = r + γ ∗ maxQ(s_t1, a_t1)

In this function, r is the reward value of the current state. The max element returns the maximal reward possible at t1 for the current state.

Another form of the formula is:
![image](https://user-images.githubusercontent.com/10816389/99918796-96101200-2d19-11eb-9db8-11a7909b71e5.png)

This requires:

- [x]  Discretized states, see #13 
- [x] Action enum, see #14 
- [x] Function to compute reward value given a state pair, see #16
